/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tomtresansky.xml_utils

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.tomtresansky.xml_utils.XmlUtilsPlugin' plugin.
 */
class XmlUtilsPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.tomtresansky.xml_utils.XmlUtilsPlugin")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
